package View;

import Control.Gerenciador;
import Control.IGerenciador;
import Model.Contato;
import java.io.IOException;
import java.text.ParseException;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class View extends javax.swing.JFrame {

    private final IGerenciador gerenciador;

    private TelefoneEmergencia telefonesEmergencia;

    private String nome, telefone1, telefone2, descricao, categoria;
    private final String[] opcoesAviso = {"Sim", "Não"};

    public View() throws ParseException, IOException, ClassNotFoundException {
        setLocation(400, 50);
        setTitle("Gestão de Contatos");
        initComponents();
        setIconImage(new ImageIcon("Icone.png").getImage());
        
        
        MaskFormatter mask1 = new MaskFormatter("(##)####-####");
        mask1.install(jFTFTelefoneCadastro1);

        MaskFormatter mask2 = new MaskFormatter("(##)####-####");
        mask2.install(jFTFTelefoneCadastro2);

        MaskFormatter mask3 = new MaskFormatter("(##)####-####");
        mask3.install(jTFTelefoneBusca);

        gerenciador = new Gerenciador();
    }

    public void limpaCampos() {
        jTFNomeContato.setText("");
        jFTFTelefoneCadastro1.setText("");
        jFTFTelefoneCadastro2.setText("");
        jTFobservacao.setText("");

        jTFNomeBusca.setText("");
        jTFTelefoneBusca.setText("");
    }

    private int criaAviso(String mensagem, String[] opcoes) {
        return JOptionPane.showOptionDialog(this, mensagem, "Contatos", 0, JOptionPane.WARNING_MESSAGE, null, opcoes,
                opcoes[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAMostraContatos = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jCBTipoBusca = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jBBuscaTipo = new javax.swing.JButton();
        jTFNomeBusca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBBuscaNome = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jBBuscaTelefone = new javax.swing.JButton();
        jTFTelefoneBusca = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jBExibeContatos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBCadastraContato = new javax.swing.JButton();
        jTFNomeContato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFobservacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBTipoCadastro = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jFTFTelefoneCadastro1 = new javax.swing.JFormattedTextField();
        jFTFTelefoneCadastro2 = new javax.swing.JFormattedTextField();
        jBContatosEmergencia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAConsole = new javax.swing.JTextArea();
        jBExcluirRegistros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane2.addTab("tab1", jTabbedPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTAMostraContatos.setColumns(20);
        jTAMostraContatos.setLineWrap(true);
        jTAMostraContatos.setRows(5);
        jTAMostraContatos.setEnabled(false);
        jScrollPane1.setViewportView(jTAMostraContatos);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCBTipoBusca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pessoal", "Farmácias", "Médicos", "Dentistas", "Oculistas", "Pizzarias", "Restaurantes", "Mercados", "Oficina", "Lojas", "Floriculturas", "Musical", "Servicos Gerais" }));

        jLabel4.setText("Tipo de Contato: ");

        jBBuscaTipo.setText("Buscar");
        jBBuscaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaTipoActionPerformed(evt);
            }
        });

        jLabel9.setText("Buscar p/ nome: ");

        jBBuscaNome.setText("Buscar");
        jBBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaNomeActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar p/ telefone:");

        jBBuscaTelefone.setText("Buscar");
        jBBuscaTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBBuscaTipo))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jCBTipoBusca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNomeBusca)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTelefoneBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBuscaNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBBuscaTelefone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscaTipo)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscaNome)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTelefoneBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscaTelefone)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel11.setText("Pesquisa");

        jLabel12.setText("Exibição");

        jBExibeContatos.setText("Exibir todos os contatos");
        jBExibeContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExibeContatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBExibeContatos)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBExibeContatos))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Consultar", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBCadastraContato.setText("Cadastrar Contato");
        jBCadastraContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastraContatoActionPerformed(evt);
            }
        });

        jLabel1.setText("(*) Nome");

        jLabel2.setText("(*) Telefone 1");

        jLabel3.setText("Descrição");

        jLabel5.setText("Telefone 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("(*) - Campos Obrigatórios");

        jCBTipoCadastro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pessoal", "Farmácias", "Médicos", "Dentistas", "Oculistas", "Pizzarias", "Restaurantes", "Mercados", "Oficina", "Lojas", "Floriculturas", "Musical", "Servicos Gerais" }));

        jLabel8.setText("(*) Tipo de Contato");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBCadastraContato)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFobservacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(jTFNomeContato, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFTFTelefoneCadastro1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFTFTelefoneCadastro2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jCBTipoCadastro, 0, 177, Short.MAX_VALUE)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTFTelefoneCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTFTelefoneCadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFobservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jBCadastraContato)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Cadastrar Contato", jPanel2);

        jBContatosEmergencia.setText("Telefones de Emergência");
        jBContatosEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContatosEmergenciaActionPerformed(evt);
            }
        });

        jTAConsole.setBackground(new java.awt.Color(155, 155, 155));
        jTAConsole.setColumns(20);
        jTAConsole.setRows(5);
        jTAConsole.setEnabled(false);
        jScrollPane2.setViewportView(jTAConsole);

        jBExcluirRegistros.setText("Excluir Registros");
        jBExcluirRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirRegistrosActionPerformed(evt);
            }
        });

        jLabel7.setText("Console");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jBExcluirRegistros)
                .addGap(10, 104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBContatosEmergencia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBContatosEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBExcluirRegistros)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastraContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastraContatoActionPerformed
        try {
            nome = jTFNomeContato.getText();
            telefone1 = jFTFTelefoneCadastro1.getText();
            telefone2 = jFTFTelefoneCadastro2.getText() + "";
            descricao = jTFobservacao.getText() + "";
            categoria = (String) jCBTipoCadastro.getSelectedItem();

            Contato novo = gerenciador.incluirContato(nome, telefone1, telefone2, descricao, categoria);

            jTAConsole.setText(novo.getNome() + " cadastrado com sucesso");
            this.limpaCampos();

        } catch (IOException ex) {
            jTAConsole.setText("Erro ao cadastrar contato.");
        } catch (IllegalArgumentException iae) {
            jTAConsole.setText(iae.getMessage());
        }
    }//GEN-LAST:event_jBCadastraContatoActionPerformed

    private void jBContatosEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContatosEmergenciaActionPerformed
        try {
            this.telefonesEmergencia = new TelefoneEmergencia();

            this.telefonesEmergencia.setVisible(true);
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        } catch (ParseException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBContatosEmergenciaActionPerformed

    private void jBExibeContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExibeContatosActionPerformed
        try {
            Collection<Contato> contatos = gerenciador.getContatos();
            String msg = "";

            for (Contato contato : contatos) {
                msg += contato.imprimeContato()
                        + "\n-------------------------------------------------------------------------------------------";
            }

            jTAMostraContatos.setText(msg);
        } catch (IllegalArgumentException iae) {
            jTAConsole.setText(iae.getMessage());
        }
    }//GEN-LAST:event_jBExibeContatosActionPerformed

    private void jBExcluirRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirRegistrosActionPerformed
        int resposta = criaAviso("Deseja realmente excluir TODOS os registros?", opcoesAviso);

        if (resposta == 0) {
            try {
                gerenciador.excluirContatos();
                jTAMostraContatos.setText("");
                jTAConsole.setText("Contatos excluidos com sucesso");

            } catch (IOException ex) {
                jTAConsole.setText("Falha ao excluir registros");
            }
        }
    }//GEN-LAST:event_jBExcluirRegistrosActionPerformed

    private void jBBuscaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaTipoActionPerformed
        try {
            Collection<Contato> cont = gerenciador.buscarPorCategoria(
                    (String) jCBTipoBusca.getSelectedItem());
            String msg = "";

            for (Contato cont1 : cont) {
                msg += cont1.imprimeContato()
                        + "\n-------------------------------------------------------------------------------------------";
            }

            jTAMostraContatos.setText(msg);
        } catch (IllegalArgumentException iae) {
            jTAConsole.setText(iae.getMessage());
        }

    }//GEN-LAST:event_jBBuscaTipoActionPerformed

    private void jBBuscaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaTelefoneActionPerformed
        try {
            Contato cont = gerenciador.buscarPorTelefone(jTFTelefoneBusca.getText());

            jTAMostraContatos.setText(cont.imprimeContato());
            this.limpaCampos();

        } catch (IllegalArgumentException iae) {
            jTAConsole.setText(iae.getMessage());
        }
    }//GEN-LAST:event_jBBuscaTelefoneActionPerformed

    private void jBBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaNomeActionPerformed
        try {
            Collection<Contato> cont = gerenciador.buscarPorNome(jTFNomeBusca.getText());
            String msg = "";

            for (Contato cont1 : cont) {
                msg += cont1.imprimeContato()
                        + "\n-------------------------------------------------------------------------------------------";
            }

            jTAMostraContatos.setText(msg);

        } catch (IllegalArgumentException iae) {
            jTAConsole.setText(iae.getMessage());
        }
    }//GEN-LAST:event_jBBuscaNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new View().setVisible(true);
                } catch (ParseException | IOException | ClassNotFoundException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBBuscaNome;
    private javax.swing.JButton jBBuscaTelefone;
    private javax.swing.JButton jBBuscaTipo;
    private javax.swing.JButton jBCadastraContato;
    private javax.swing.JButton jBContatosEmergencia;
    private javax.swing.JButton jBExcluirRegistros;
    private javax.swing.JButton jBExibeContatos;
    private javax.swing.JComboBox jCBTipoBusca;
    private javax.swing.JComboBox jCBTipoCadastro;
    private javax.swing.JFormattedTextField jFTFTelefoneCadastro1;
    private javax.swing.JFormattedTextField jFTFTelefoneCadastro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAConsole;
    private javax.swing.JTextArea jTAMostraContatos;
    private javax.swing.JTextField jTFNomeBusca;
    private javax.swing.JTextField jTFNomeContato;
    private javax.swing.JFormattedTextField jTFTelefoneBusca;
    private javax.swing.JTextField jTFobservacao;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
